image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - mv /builds/kirklange/kirklange.gitlab.io/.Gemfile /builds/kirklange/kirklange.gitlab.io/Gemfile
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
